### ISSUE TITLE
Chess: Actual threefold rule triggered as 50-move rule

### ISSUE THREAD

**Issue by MasterCash** [siggame/Cerveau#32]
The function used to handle 50-move rule using internal check for actual threefold rule which forces both the simplified and non simplified threefold rule to be followed else trigger a draw for full threefold rule disguised as a 50-move draw.

**Comment by JacobFischer** [comment]
It might be helpful to check out how V1 chess determined 50-move rule and ensure it is the same in this V2: https://github.com/siggame/Cerveau/tree/v1

**Comment by MasterCash** [comment]
Fixed
