### ISSUE TITLE
Chess cannot send FEN string via --gameSettings

### ISSUE THREAD

**Issue by MasterCash** [siggame/Cerveau#33]
sending an fen string to the game server does nothing. game starts with default state.

**Comment by JacobFischer** [comment]
Ugh I broke it again didn't I?

**Comment by MasterCash** [comment]
I think it was introduced when you fixed the 15 minute default issue. It seems that it doesn't accept anything or overrides it with the default.

**Comment by JacobFischer** [comment]
Fixed in aa5cc77139cb565348c4e4b63227b06249a13e17
