### ISSUE TITLE
Some game settings are hidden on the webserver

### ISSUE THREAD

**Issue by Tarnasa** [siggame/Cerveau#36]
As seen below, some of the later "game settings" are hidden underneath "Active Rooms in Lobby".

![2019-05-02_22-09-31](https://user-images.githubusercontent.com/4990790/57120614-6492b880-6d27-11e9-9b36-b97e173bef87.png)

**Comment by JacobFischer** [comment]
Good catch. Made the height used fo css animation variable in 968dc32c288b8a53591eee0ab5402e90847d3205
