### ISSUE TITLE
Graceful Shutdown

### ISSUE THREAD

**Issue by JacobFischer** [siggame/Cerveau#6]
When Cerveau gets a SIGINT (Ctrl + C) it should gracefully shut down. That means it should:
1. Disconnect any Lobbied clients with a `fatal` event, and a message explaining the server is shutting down.
2. Wait for all game sessions to exit, and log them as normal
3. If any more connections come in while waiting to shut down give them the same `fatal` event as in 1, then disconnect them.

Once all game sessions have exited gracefully Cerveau can shut down too, and no one is forced out of a game.

If another SIGINT is received during this shutdown it should just force shutdown the whole thing.

Note: Node.js exposes an easy hook for the SIGINT event: https://nodejs.org/api/readline.html#readline_event_sigint

**Comment by JacobFischer** [comment]
ec13145 was for siggame/Cerveai-MegaMinerAI-Dev

**Comment by KendallHarter** [comment]
When running on Windows, neither control+C nor control+\ causes the server to stop running.

**Comment by JacobFischer** [comment]
Works for me in Windows 10 in PowerShell and cmd:

![image](https://cloud.githubusercontent.com/assets/1050503/13396146/a96bb192-deb8-11e5-9f2d-5b8cd7411e55.png)

![image](https://cloud.githubusercontent.com/assets/1050503/13396151/b1253318-deb8-11e5-88a6-9070bbd11074.png)

How are you running it? Maybe your terminal is not sending the SIGINT? If you notice I only hook into the SIGINT event because the [Node.js documentation](https://nodejs.org/api/readline.html#readline_event_sigint) states the rest do not work on Windows, but SIGINT will.

**Comment by KendallHarter** [comment]
Strange, I do the same thing but it doesn't terminate.  I have Node.js version 4.1.1, I'll try updating to v5.7.0 and see if that works.

**Comment by KendallHarter** [comment]
Updating to v5.7.0 did not fix the issue.  I don't understand why this works for you but not for me.

**Comment by JacobFischer** [comment]
I'm running v4.3.1 LTS on Windows. v5 changes a lot so I've not done the research to see if it is forwards compatible.

**Comment by KendallHarter** [comment]
Hm, this works properly on v4.3.1 LTS on Windows.
Perhaps have a note that this feature does not work correctly on v5.7.0 or something.
